/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.*;
import javax.swing.JOptionPane;
import modelo.ArchivoTexto;

public class VentanaPrincipal extends javax.swing.JFrame {
    
    /*
     Repositorio donde se guardan los objetos del sistema
     */
    Repositorio repo = new Repositorio();

    /*
     Clase para guardar en archivo de texto
     */
    ArchivoTexto archivo = new ArchivoTexto();

    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar Cliente");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Agregar Suplemento");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Mostrar Datos");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Guardar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jButton3)
                                .addGap(29, 29, 29)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(65, 65, 65)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*
     Botón para agregar cliente de forma interactiva.
     Se piden los datos usando cuadros de diálogo.
         */

        try {

            // Pedir ID
            int id = Integer.parseInt(
                    javax.swing.JOptionPane.showInputDialog("Ingrese ID")
            );

            // Pedir nombre
            String nombre
                    = javax.swing.JOptionPane.showInputDialog("Ingrese nombre");

            // Pedir membresia
            String membresia
                    = javax.swing.JOptionPane.showInputDialog("Ingrese membresia");

            // Crear objeto cliente
            Cliente c = new Cliente(nombre, id, membresia);

            // Guardar en repositorio
            repo.agregarCliente(c);

            // Mostrar en pantalla
            jTextArea1.append(
                    "Cliente agregado: "
                    + c.getNombre()
                    + " ID: "
                    + c.getId()
                    + " Membresia: "
                    + c.getMembresia()
                    + "\n"
            );

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error al ingresar datos"
            );

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*
     Botón para agregar suplemento de forma interactiva.

     Se pide al usuario el nombre y el precio del suplemento
     usando cuadros de diálogo (JOptionPane).

     Luego se crea el objeto Suplemento y se guarda en el
     repositorio.
         */

        try {

            // Pedir nombre del suplemento
            String nombre
                    = javax.swing.JOptionPane.showInputDialog(
                            "Ingrese nombre del suplemento"
                    );

            // Pedir precio del suplemento
            double precio = Double.parseDouble(
                    javax.swing.JOptionPane.showInputDialog(
                            "Ingrese precio"
                    )
            );

            // Crear objeto Suplemento usando el constructor correcto
            Suplemento s = new Suplemento(nombre, precio);

            // Guardar en el repositorio
            repo.agregarSuplemento(s);

            // Mostrar en el área de texto
            jTextArea1.append(
                    "Suplemento agregado: "
                    + s.getNombre()
                    + " Precio: "
                    + s.getPrecio()
                    + "\n"
            );

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error al ingresar datos"
            );

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        /*
     Botón Mostrar Datos

     Este botón muestra todos los clientes y suplementos
     guardados en el repositorio.

     Los datos se imprimen en el JTextArea.
    */

    // limpiar el área de texto
    jTextArea1.setText("");


    // ===== MOSTRAR CLIENTES =====

    jTextArea1.append("----- CLIENTES -----\n");

    for (Cliente c : repo.getClientes()) {

        jTextArea1.append(
                c.getNombre()
                + "  ID: "
                + c.getId()
                + "  Membresia: "
                + c.getMembresia()
                + "\n"
        );

    }


    // ===== MOSTRAR SUPLEMENTOS =====

    jTextArea1.append("\n----- SUPLEMENTOS -----\n");

    for (Suplemento s : repo.getSuplementos()) {

        jTextArea1.append(
                s.getNombre()
                + "  Precio: "
                + s.getPrecio()
                + "\n"
        );

    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        /*
     Botón Guardar

     Guarda el contenido del JTextArea
     en el archivo datos.txt usando ArchivoTexto
         */

        // obtener el texto del area
        String texto = jTextArea1.getText();
      
        // guardar el texto en el archivo
        archivo.guardar(texto);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
